-- Links real course-requirement rows to the 7 Humanities & Social Sciences
-- careers added to js/data.js (teacher, social-worker, graphic-designer,
-- photographer, filmmaker, musician, dancer). Reviewed manually against the
-- full candidate list before writing this file.
--
-- "dancer" has NO rows here on purpose -- there is no dedicated dance/
-- choreography degree in the dataset. The closest matches (Drama, Theatre
-- and Performance degrees) train a meaningfully different skill set, so
-- linking them would misrepresent real entry requirements. That career
-- just runs on the free-text guidance in data.js until real dance-specific
-- course data is available.
--
-- Run ONCE in the Supabase SQL Editor. There is no unique constraint on
-- (careerId, courseRequirementId), so running this twice will duplicate
-- rows -- if you need to re-run it, first do:
--   DELETE FROM "careerCourseLinks" WHERE "careerId" IN ('teacher', 'social-worker', 'graphic-designer', 'photographer', 'filmmaker', 'musician');

INSERT INTO "careerCourseLinks" ("careerId", "courseRequirementId", "matchType", "matchedKeywords")
VALUES
  ('teacher', 668, 'exact', 'education'),
  ('teacher', 344, 'exact', 'education'),
  ('teacher', 345, 'exact', 'education'),
  ('teacher', 346, 'exact', 'education'),
  ('teacher', 347, 'exact', 'education'),
  ('teacher', 349, 'exact', 'education'),
  ('teacher', 348, 'exact', 'education'),
  ('teacher', 350, 'exact', 'education'),
  ('teacher', 323, 'exact', 'education'),
  ('teacher', 403, 'exact', 'education'),
  ('teacher', 325, 'exact', 'education'),
  ('teacher', 324, 'exact', 'education'),
  ('teacher', 330, 'exact', 'education'),
  ('teacher', 332, 'exact', 'education'),
  ('teacher', 341, 'exact', 'education'),
  ('teacher', 336, 'exact', 'education'),
  ('teacher', 326, 'exact', 'education'),
  ('teacher', 335, 'exact', 'education'),
  ('teacher', 328, 'exact', 'education'),
  ('teacher', 327, 'exact', 'education'),
  ('teacher', 340, 'exact', 'education'),
  ('teacher', 334, 'exact', 'education'),
  ('teacher', 333, 'exact', 'education'),
  ('teacher', 331, 'exact', 'education'),
  ('teacher', 338, 'exact', 'education'),
  ('teacher', 329, 'exact', 'education'),
  ('teacher', 337, 'exact', 'education'),
  ('teacher', 339, 'exact', 'education'),
  ('teacher', 342, 'exact', 'education'),
  ('teacher', 343, 'exact', 'education'),
  ('teacher', 418, 'exact', 'education'),
  ('teacher', 430, 'exact', 'education'),
  ('teacher', 377, 'exact', 'education'),
  ('teacher', 416, 'exact', 'education'),
  ('teacher', 419, 'exact', 'education'),
  ('teacher', 517, 'exact', 'education'),
  ('teacher', 417, 'exact', 'education'),
  ('teacher', 426, 'exact', 'education'),
  ('teacher', 378, 'exact', 'education'),
  ('teacher', 404, 'exact', 'education'),
  ('teacher', 420, 'exact', 'education'),
  ('teacher', 518, 'exact', 'education'),
  ('teacher', 431, 'exact', 'education'),
  ('teacher', 432, 'exact', 'education'),
  ('teacher', 434, 'exact', 'education'),
  ('teacher', 433, 'exact', 'education'),
  ('teacher', 435, 'exact', 'education'),
  ('teacher', 423, 'exact', 'education'),
  ('teacher', 424, 'exact', 'education'),
  ('teacher', 425, 'exact', 'education'),
  ('teacher', 422, 'exact', 'education'),
  ('teacher', 519, 'exact', 'education'),
  ('teacher', 421, 'exact', 'education'),
  ('teacher', 373, 'exact', 'education'),
  ('teacher', 374, 'exact', 'education'),
  ('teacher', 375, 'exact', 'education'),
  ('teacher', 376, 'exact', 'education'),
  ('teacher', 351, 'exact', 'education'),
  ('teacher', 372, 'exact', 'education'),
  ('teacher', 366, 'exact', 'education'),
  ('teacher', 353, 'exact', 'education'),
  ('teacher', 409, 'exact', 'education'),
  ('teacher', 352, 'exact', 'education'),
  ('teacher', 354, 'exact', 'education'),
  ('teacher', 410, 'exact', 'education'),
  ('teacher', 355, 'exact', 'education'),
  ('teacher', 356, 'exact', 'education'),
  ('teacher', 357, 'exact', 'education'),
  ('teacher', 358, 'exact', 'education'),
  ('teacher', 359, 'exact', 'education'),
  ('teacher', 360, 'exact', 'education'),
  ('teacher', 361, 'exact', 'education'),
  ('teacher', 362, 'exact', 'education'),
  ('teacher', 411, 'exact', 'education'),
  ('teacher', 367, 'exact', 'education'),
  ('teacher', 406, 'exact', 'education'),
  ('teacher', 405, 'exact', 'education'),
  ('teacher', 379, 'exact', 'education'),
  ('teacher', 382, 'exact', 'education'),
  ('teacher', 381, 'exact', 'education'),
  ('teacher', 380, 'exact', 'education'),
  ('teacher', 390, 'exact', 'education'),
  ('teacher', 401, 'exact', 'education'),
  ('teacher', 400, 'exact', 'education'),
  ('teacher', 402, 'exact', 'education'),
  ('teacher', 396, 'exact', 'education'),
  ('teacher', 399, 'exact', 'education'),
  ('teacher', 393, 'exact', 'education'),
  ('teacher', 394, 'exact', 'education'),
  ('teacher', 397, 'exact', 'education'),
  ('teacher', 395, 'exact', 'education'),
  ('teacher', 398, 'exact', 'education'),
  ('teacher', 392, 'exact', 'education'),
  ('teacher', 391, 'exact', 'education'),
  ('teacher', 387, 'exact', 'education'),
  ('teacher', 384, 'exact', 'education'),
  ('teacher', 385, 'exact', 'education'),
  ('teacher', 388, 'exact', 'education'),
  ('teacher', 389, 'exact', 'education'),
  ('teacher', 383, 'exact', 'education'),
  ('teacher', 386, 'exact', 'education'),
  ('teacher', 369, 'exact', 'education'),
  ('teacher', 370, 'exact', 'education'),
  ('teacher', 371, 'exact', 'education'),
  ('teacher', 368, 'exact', 'education'),
  ('teacher', 415, 'exact', 'education'),
  ('teacher', 414, 'exact', 'education'),
  ('teacher', 413, 'exact', 'education'),
  ('teacher', 412, 'exact', 'education'),
  ('teacher', 318, 'exact', 'education'),
  ('teacher', 319, 'exact', 'education'),
  ('teacher', 320, 'exact', 'education'),
  ('teacher', 322, 'exact', 'education'),
  ('teacher', 321, 'exact', 'education'),
  ('teacher', 407, 'exact', 'education'),
  ('teacher', 363, 'exact', 'education'),
  ('teacher', 364, 'exact', 'education'),
  ('teacher', 365, 'exact', 'education'),
  ('teacher', 408, 'exact', 'education'),
  ('teacher', 429, 'exact', 'education'),
  ('social-worker', 675, 'exact', 'social work'),
  ('social-worker', 1301, 'exact', 'social work'),
  ('social-worker', 637, 'exact', 'social work'),
  ('social-worker', 1296, 'exact', 'social work'),
  ('social-worker', 602, 'exact', 'social work'),
  ('social-worker', 497, 'exact', 'social work'),
  ('social-worker', 572, 'exact', 'social work'),
  ('social-worker', 714, 'exact', 'social work'),
  ('social-worker', 546, 'exact', 'social work'),
  ('social-worker', 522, 'exact', 'social work'),
  ('social-worker', 267, 'exact', 'social work'),
  ('social-worker', 450, 'exact', 'social work'),
  ('graphic-designer', 677, 'approximate', 'visual art'),
  ('graphic-designer', 547, 'approximate', 'visual art'),
  ('graphic-designer', 452, 'exact', 'graphic design'),
  ('graphic-designer', 453, 'exact', 'graphic design'),
  ('graphic-designer', 680, 'approximate', 'visual art'),
  ('graphic-designer', 814, 'approximate', 'multimedia design'),
  ('graphic-designer', 682, 'exact', 'graphic design'),
  ('graphic-designer', 1264, 'approximate', 'multimedia design'),
  ('graphic-designer', 1265, 'approximate', 'multimedia design'),
  ('photographer', 683, 'exact', 'photography'),
  ('filmmaker', 514, 'exact', 'film and television'),
  ('filmmaker', 526, 'exact', 'film and television'),
  ('filmmaker', 565, 'exact', 'film and television'),
  ('musician', 502, 'exact', 'music'),
  ('musician', 473, 'exact', 'music'),
  ('musician', 474, 'exact', 'music'),
  ('musician', 475, 'exact', 'music'),
  ('musician', 503, 'exact', 'music'),
  ('musician', 691, 'exact', 'music'),
  ('musician', 516, 'exact', 'music'),
  ('musician', 530, 'exact', 'music'),
  ('musician', 532, 'exact', 'music'),
  ('musician', 541, 'exact', 'music'),
  ('musician', 542, 'exact', 'music'),
  ('musician', 543, 'exact', 'music'),
  ('musician', 544, 'exact', 'music'),
  ('musician', 597, 'exact', 'music'),
  ('musician', 598, 'exact', 'music'),
  ('musician', 611, 'exact', 'music'),
  ('musician', 612, 'exact', 'music'),
  ('musician', 618, 'exact', 'music'),
  ('musician', 619, 'exact', 'music'),
  ('musician', 670, 'exact', 'music'),
  ('musician', 671, 'exact', 'music'),
  ('musician', 685, 'exact', 'music'),
  ('musician', 686, 'exact', 'music'),
  ('musician', 687, 'exact', 'music'),
  ('musician', 688, 'exact', 'music'),
  ('musician', 692, 'exact', 'music'),
  ('musician', 713, 'exact', 'music'),
  ('musician', 689, 'exact', 'music'),
  ('musician', 690, 'exact', 'music')
;
