/* ============================================================
   TLOU INSTITUTE CAREER PATHWAY — DATA MODULE
   Original data model & seed content. Not derived from any
   third-party product's proprietary text or design.
   ============================================================ */

const FACULTIES = [
  { id: 'engineering',   name: 'Engineering',                 color: '#3B2E7A', tag: 'ENG' },
  { id: 'ict',           name: 'ICT & Computer Science',      color: '#2F8FFF', tag: 'ICT' },
  { id: 'health',        name: 'Health Sciences',             color: '#1FA25A', tag: 'HLT' },
  { id: 'natsci',        name: 'Natural Sciences',            color: '#00A896', tag: 'SCI' },
  { id: 'built',         name: 'Built Environment',           color: '#C7860B', tag: 'BLT' },
  { id: 'agri',          name: 'Agriculture',                 color: '#5B8A00', tag: 'AGR' },
  { id: 'finance',       name: 'Finance, Actuarial & Quant',  color: '#C8305A', tag: 'FIN' },
];

function facultyById(id){ return FACULTIES.find(f=>f.id===id) || FACULTIES[0]; }

// RIASEC-style interest dimensions used for the assessment
const RIASEC = [
  { id:'R', name:'Practical & Hands-on', desc:'Working with tools, machines, the outdoors or your hands.' },
  { id:'I', name:'Investigative & Analytical', desc:'Solving problems, researching, working with data and ideas.' },
  { id:'A', name:'Creative & Expressive', desc:'Designing, creating, imagining new things.' },
  { id:'S', name:'People-focused', desc:'Helping, teaching, caring for or supporting others.' },
  { id:'E', name:'Enterprising & Persuasive', desc:'Leading, selling, starting things, taking initiative.' },
  { id:'C', name:'Organised & Precise', desc:'Working with structure, numbers, records and detail.' },
];

const STRENGTH_KEYS = [
  { id:'maths', label:'Mathematics' },
  { id:'sciences', label:'Sciences' },
  { id:'language', label:'Languages & Communication' },
  { id:'problem', label:'Problem-Solving & Logic' },
  { id:'tech', label:'Technology & Computers' },
  { id:'creative', label:'Creativity & Design' },
  { id:'leadership', label:'Leadership & Business' },
  { id:'practical', label:'Hands-on & Practical Skills' },
];

// 24 Likert questions (1-5), 4 per RIASEC dimension
const RIASEC_QUESTIONS = [
  { dim:'R', text:'I enjoy building, fixing or taking things apart to see how they work.' },
  { dim:'R', text:'I would rather be outdoors or in a workshop than sitting at a desk all day.' },
  { dim:'R', text:'I like working with tools, machinery or physical materials.' },
  { dim:'R', text:'I prefer clear, practical tasks over long discussions or theory.' },
  { dim:'I', text:'I like figuring out puzzles, patterns or how systems work.' },
  { dim:'I', text:'I enjoy asking "why" and digging into how or why something happens.' },
  { dim:'I', text:'I like working with numbers, data or scientific ideas.' },
  { dim:'I', text:'I enjoy research projects more than repetitive tasks.' },
  { dim:'A', text:'I like coming up with original ideas, designs or ways of doing things.' },
  { dim:'A', text:'I enjoy art, music, writing, design or other creative expression.' },
  { dim:'A', text:'I prefer open-ended tasks where I can be imaginative.' },
  { dim:'A', text:'I like making things look good, not just work well.' },
  { dim:'S', text:'I enjoy helping classmates, friends or family solve problems.' },
  { dim:'S', text:'I would enjoy a career focused on caring for or teaching people.' },
  { dim:'S', text:'People often come to me for advice or support.' },
  { dim:'S', text:'I feel motivated when my work makes a difference to other people.' },
  { dim:'E', text:'I like taking the lead on group projects.' },
  { dim:'E', text:'I enjoy persuading people or pitching an idea.' },
  { dim:'E', text:'I would enjoy starting or running my own business one day.' },
  { dim:'E', text:'I like competition and setting ambitious goals.' },
  { dim:'C', text:'I like things to be organised, accurate and in order.' },
  { dim:'C', text:'I am comfortable working with spreadsheets, records or detailed rules.' },
  { dim:'C', text:'I prefer clear instructions and structured tasks.' },
  { dim:'C', text:'I double-check my work carefully before handing it in.' },
];

// South African NSC subject list (used for subject-selection UI)
const SA_SUBJECTS = [
  'English Home Language', 'English First Additional Language',
  'Afrikaans Home Language', 'Afrikaans First Additional Language',
  'isiZulu Home Language', 'isiXhosa Home Language', 'Sesotho Home Language',
  'Setswana Home Language', 'Life Orientation',
  'Physical Sciences', 'Life Sciences', 'Accounting', 'Business Studies',
  'Economics', 'Geography', 'History', 'Information Technology',
  'Computer Applications Technology', 'Agricultural Sciences',
  'Engineering Graphics and Design', 'Consumer Studies', 'Tourism',
  'Visual Arts', 'Dramatic Arts', 'Music', 'Mathematics', 'Mathematical Literacy',
];

const CORE_ELECTIVES = SA_SUBJECTS.filter(s => ![
  'Mathematics','Mathematical Literacy','Life Orientation'
].includes(s) && !s.includes('Home Language') && !s.includes('First Additional'));

// Well-known SA public universities & TVET reference lists (general — always verify)
const UNIVERSITIES = [
  'University of Cape Town (UCT)', 'University of the Witwatersrand (Wits)',
  'Stellenbosch University (SU)', 'University of Pretoria (UP)',
  'University of Johannesburg (UJ)', 'University of KwaZulu-Natal (UKZN)',
  'North-West University (NWU)', 'University of the Free State (UFS)',
  'Rhodes University (RU)', 'Nelson Mandela University (NMU)',
  'University of the Western Cape (UWC)', 'University of South Africa (UNISA)',
  'Sefako Makgatho Health Sciences University (SMU)',
  'University of Limpopo (UL)', 'University of Venda (Univen)',
  'Walter Sisulu University (WSU)', 'University of Zululand (UniZulu)',
  'University of Mpumalanga (UMP)', 'Sol Plaatje University (SPU)',
];
const TVET_NOTE = 'Public TVET colleges (a national network of 50 colleges) offer NCV and Report 191 programmes in this field. Search "TVET colleges near me" via the Department of Higher Education and Training (dhet.gov.za) to find your nearest campus.';
const UOT = [
  'Cape Peninsula University of Technology (CPUT)', 'Tshwane University of Technology (TUT)',
  'Durban University of Technology (DUT)', 'Vaal University of Technology (VUT)',
  'Central University of Technology (CUT)', 'Mangosuthu University of Technology (MUT)',
];

/* ============================================================
   CAREER DATA MODEL
   {
     id, name, faculty, blurb, dayInLife,
     riasec:[dim,dim], strengths:[key,...],
     requiredSubjects:[{subject,necessity:'required'|'recommended', note}],
     recommendedMarks:[{subject, pct}],
     apsGuidance:{typical:'lo-hi', note},
     pathways:[{type:'University'|'TVET'|'Work-integrated', qualification, duration}],
     institutions:{universities:[...], utech:[...], tvet: bool},
     applicationNotes,
     videoQuery
   }
   ============================================================ */
const CAREERS = [
// ---------------- ENGINEERING ----------------
{ id:'civil-engineer', name:'Civil Engineer', faculty:'engineering',
  blurb:'Designs and oversees construction of infrastructure — roads, bridges, water systems, buildings and dams.',
  dayInLife:'Site visits, structural calculations, reviewing drawings, coordinating with contractors and checking safety compliance.',
  riasec:['R','I'], strengths:['maths','sciences','problem','practical'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:70},{subject:'Physical Sciences',pct:65}],
  apsGuidance:{typical:'32–40', note:'Highly competitive at top engineering faculties; some universities also use a separate faculty point score.'},
  pathways:[
    {type:'University', qualification:'BEng / BSc (Eng) Civil Engineering', duration:'4 years'},
    {type:'TVET', qualification:'National Diploma: Civil Engineering (Engineering Studies)', duration:'3 years + experiential learning'},
  ],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)','University of Pretoria (UP)','University of KwaZulu-Natal (UKZN)'], utech:['Tshwane University of Technology (TUT)','Cape Peninsula University of Technology (CPUT)'], tvet:true},
  applicationNotes:'Register with ECSA (Engineering Council of South Africa) after graduating. Most engineering faculties require a strong NBT (National Benchmark Test) result alongside NSC marks.',
  videoQuery:'day in the life of a civil engineer South Africa' },

{ id:'mechanical-engineer', name:'Mechanical Engineer', faculty:'engineering',
  blurb:'Designs, builds and maintains machines, engines, vehicles and mechanical systems.',
  dayInLife:'CAD design work, testing prototypes, running simulations, and solving mechanical failures on-site or in a lab.',
  riasec:['R','I'], strengths:['maths','sciences','problem','practical'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:70},{subject:'Physical Sciences',pct:70}],
  apsGuidance:{typical:'33–42', note:'Some of the most competitive programmes in the country — check each university\'s specific faculty score.'},
  pathways:[
    {type:'University', qualification:'BEng / BSc (Eng) Mechanical Engineering', duration:'4 years'},
    {type:'TVET', qualification:'National Diploma: Mechanical Engineering', duration:'3 years + experiential learning'},
  ],
  institutions:{universities:['University of the Witwatersrand (Wits)','University of Cape Town (UCT)','University of Pretoria (UP)','Stellenbosch University (SU)','North-West University (NWU)'], utech:['Vaal University of Technology (VUT)','Durban University of Technology (DUT)'], tvet:true},
  applicationNotes:'ECSA registration after graduating (Candidate then Professional Engineer). Engineering Graphics and Design is a helpful (not always required) elective.',
  videoQuery:'day in the life of a mechanical engineer South Africa' },

{ id:'electrical-engineer', name:'Electrical Engineer', faculty:'engineering',
  blurb:'Designs and maintains electrical systems, power networks, control systems and electronics.',
  dayInLife:'Circuit design, testing equipment, project planning, and troubleshooting power or control systems.',
  riasec:['I','R'], strengths:['maths','sciences','problem','tech'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:70},{subject:'Physical Sciences',pct:70}],
  apsGuidance:{typical:'32–40', note:'Varies significantly by university and specialisation (power, electronics, computer engineering).'},
  pathways:[
    {type:'University', qualification:'BEng / BSc (Eng) Electrical Engineering', duration:'4 years'},
    {type:'TVET', qualification:'National Diploma: Electrical Engineering', duration:'3 years + experiential learning'},
  ],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','University of Pretoria (UP)','Stellenbosch University (SU)'], utech:['Tshwane University of Technology (TUT)','Cape Peninsula University of Technology (CPUT)'], tvet:true},
  applicationNotes:'ECSA registration path after graduating. Information Technology as an elective can be a helpful bridge into electronics/computer engineering streams.',
  videoQuery:'day in the life of an electrical engineer South Africa' },

{ id:'chemical-engineer', name:'Chemical Engineer', faculty:'engineering',
  blurb:'Designs processes that turn raw materials into useful products — fuels, chemicals, food, pharmaceuticals.',
  dayInLife:'Process design, lab analysis, plant monitoring and improving efficiency/safety of production processes.',
  riasec:['I','R'], strengths:['maths','sciences','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:70},{subject:'Physical Sciences',pct:70}],
  apsGuidance:{typical:'34–42', note:'One of the most competitive engineering streams at most universities.'},
  pathways:[{type:'University', qualification:'BEng / BSc (Eng) Chemical Engineering', duration:'4 years'}],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)','University of Pretoria (UP)','North-West University (NWU)'], utech:[], tvet:false},
  applicationNotes:'ECSA registration after graduating. Strong Physical Sciences and Mathematics results are essential for competitive selection.',
  videoQuery:'day in the life of a chemical engineer South Africa' },

{ id:'industrial-engineer', name:'Industrial Engineer', faculty:'engineering',
  blurb:'Improves how systems, factories and organisations work — optimising processes, cost, quality and people.',
  dayInLife:'Analysing workflows, building efficiency models, project management, and process improvement studies.',
  riasec:['I','C'], strengths:['maths','problem','leadership'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:65},{subject:'Physical Sciences',pct:60}],
  apsGuidance:{typical:'30–38', note:'Slightly more flexible entry than some other engineering streams, but still competitive.'},
  pathways:[{type:'University', qualification:'BEng / BSc (Eng) Industrial Engineering', duration:'4 years'}],
  institutions:{universities:['University of Pretoria (UP)','Stellenbosch University (SU)','University of the Witwatersrand (Wits)','University of Johannesburg (UJ)'], utech:[], tvet:false},
  applicationNotes:'A strong blend of mathematics, logic and business thinking — a good fit for STEM-minded learners who also enjoy leadership and organisation.',
  videoQuery:'what does an industrial engineer do South Africa' },

{ id:'mechatronics-engineer', name:'Mechatronics Engineer', faculty:'engineering',
  blurb:'Combines mechanical, electronic and software engineering to design robots and automated systems.',
  dayInLife:'Designing robotic systems, writing embedded software, and integrating sensors, motors and control logic.',
  riasec:['R','I'], strengths:['maths','sciences','tech','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:70},{subject:'Physical Sciences',pct:65}],
  apsGuidance:{typical:'32–40', note:'A newer, growing field — check which universities offer it as a distinct programme vs a specialisation.'},
  pathways:[{type:'University', qualification:'BEng Mechatronics / Electromechanical Engineering', duration:'4 years'}],
  institutions:{universities:['Stellenbosch University (SU)','University of Johannesburg (UJ)','University of Pretoria (UP)'], utech:['Cape Peninsula University of Technology (CPUT)'], tvet:false},
  applicationNotes:'Great fit for learners who enjoy both hardware and coding. Information Technology as an elective is a strong complement.',
  videoQuery:'what is mechatronics engineering' },

// ---------------- ICT / COMPUTER SCIENCE ----------------
{ id:'software-developer', name:'Software Developer', faculty:'ict',
  blurb:'Designs, builds and maintains applications, websites and software systems.',
  dayInLife:'Writing and testing code, fixing bugs, reviewing teammates\' work, and planning new features.',
  riasec:['I','R'], strengths:['tech','problem','maths'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Information Technology',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:60},{subject:'Information Technology',pct:60}],
  apsGuidance:{typical:'28–36', note:'Entry requirements vary a lot — some diploma/degree routes accept Mathematics without IT as a subject.'},
  pathways:[
    {type:'University', qualification:'BSc Computer Science / BCom Information Systems', duration:'3 years'},
    {type:'TVET', qualification:'National Diploma: Information Technology', duration:'3 years'},
  ],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)','University of Pretoria (UP)','University of Johannesburg (UJ)'], utech:['Durban University of Technology (DUT)','Tshwane University of Technology (TUT)'], tvet:true},
  applicationNotes:'Many successful developers also enter via coding bootcamps or self-teaching plus a portfolio — but a formal qualification widens options and is required for some employers/visas.',
  videoQuery:'day in the life of a software developer South Africa' },

{ id:'data-scientist', name:'Data Scientist', faculty:'ict',
  blurb:'Analyses large datasets to find patterns and insights that guide business or scientific decisions.',
  dayInLife:'Cleaning data, building statistical/ML models, and presenting findings to decision-makers.',
  riasec:['I','C'], strengths:['maths','tech','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:75}],
  apsGuidance:{typical:'32–40', note:'Often entered via Computer Science, Statistics, Mathematics or Actuarial Science degrees.'},
  pathways:[{type:'University', qualification:'BSc Computer Science / Statistics / Data Science', duration:'3 years, often + Honours'}],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)','University of Pretoria (UP)'], utech:[], tvet:false},
  applicationNotes:'Strong Mathematics is essential. An Honours or Master\'s degree is common for senior data science roles.',
  videoQuery:'what does a data scientist do' },

{ id:'network-engineer', name:'Computer / Network Systems Engineer', faculty:'ict',
  blurb:'Designs, builds and maintains the networks and infrastructure that keep organisations connected.',
  dayInLife:'Configuring servers and networks, monitoring systems, and resolving connectivity or security issues.',
  riasec:['R','I'], strengths:['tech','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'recommended'},{subject:'Information Technology',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:55}],
  apsGuidance:{typical:'26–32', note:'Diploma and certificate routes (e.g. Cisco, CompTIA) are common alongside formal qualifications.'},
  pathways:[
    {type:'University', qualification:'BSc/BTech Information Technology', duration:'3 years'},
    {type:'TVET', qualification:'National Diploma: Information Technology (Networking stream)', duration:'3 years'},
  ],
  institutions:{universities:['University of Johannesburg (UJ)','North-West University (NWU)'], utech:['Cape Peninsula University of Technology (CPUT)','Tshwane University of Technology (TUT)'], tvet:true},
  applicationNotes:'Industry certifications (Cisco CCNA, CompTIA Network+) are widely recognised alongside a formal qualification.',
  videoQuery:'what does a network engineer do' },

{ id:'cybersecurity-specialist', name:'Cybersecurity Specialist', faculty:'ict',
  blurb:'Protects organisations\' systems and data from hacking, fraud and cyber-attacks.',
  dayInLife:'Monitoring systems for threats, running security tests, and responding to security incidents.',
  riasec:['I','C'], strengths:['tech','problem','maths'],
  requiredSubjects:[{subject:'Mathematics',necessity:'recommended'},{subject:'Information Technology',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:60}],
  apsGuidance:{typical:'28–36', note:'A fast-growing field with routes via Computer Science, IT or specialised cybersecurity diplomas.'},
  pathways:[{type:'University', qualification:'BSc Computer Science / Information Technology (Security stream)', duration:'3 years'}],
  institutions:{universities:['University of Johannesburg (UJ)','University of Pretoria (UP)','Rhodes University (RU)'], utech:['Nelson Mandela University (NMU)'], tvet:true},
  applicationNotes:'Certifications (CompTIA Security+, CEH, CISSP later in career) are highly valued alongside a degree.',
  videoQuery:'what does a cybersecurity analyst do' },

{ id:'it-business-analyst', name:'IT / Systems Business Analyst', faculty:'ict',
  blurb:'Bridges business needs and technology — analysing problems and designing digital solutions.',
  dayInLife:'Interviewing stakeholders, mapping business processes, and writing specifications for developers.',
  riasec:['E','C'], strengths:['problem','language','leadership'],
  requiredSubjects:[{subject:'Mathematics',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:55}],
  apsGuidance:{typical:'28–34', note:'Often entered via a BCom Information Systems or similar business-and-tech degree.'},
  pathways:[{type:'University', qualification:'BCom Information Systems', duration:'3 years'}],
  institutions:{universities:['University of Cape Town (UCT)','University of Pretoria (UP)','University of Johannesburg (UJ)'], utech:[], tvet:false},
  applicationNotes:'A strong choice for learners who like both technology and working with people/business problems.',
  videoQuery:'what does a business analyst do IT' },

// ---------------- HEALTH SCIENCES ----------------
{ id:'medical-doctor', name:'Medical Doctor', faculty:'health',
  blurb:'Diagnoses and treats illness and injury, promoting health across hospitals, clinics and communities.',
  dayInLife:'Consultations, ward rounds, diagnostics, and ongoing study — a demanding but purpose-driven career.',
  riasec:['I','S'], strengths:['sciences','problem','language'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'},{subject:'Life Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:70},{subject:'Physical Sciences',pct:70},{subject:'Life Sciences',pct:70}],
  apsGuidance:{typical:'36–42+', note:'Among the most competitive programmes in the country; many universities also require a National Benchmark Test (NBT) and/or interview.'},
  pathways:[{type:'University', qualification:'MBChB (Bachelor of Medicine & Surgery)', duration:'6 years + 2 years internship + 1 year community service'}],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)','University of Pretoria (UP)','University of KwaZulu-Natal (UKZN)','Sefako Makgatho Health Sciences University (SMU)','Walter Sisulu University (WSU)'], utech:[], tvet:false},
  applicationNotes:'Register with the Health Professions Council of South Africa (HPCSA). Selection also considers a personal statement, sometimes an interview, and quintile/redress factors at some universities.',
  videoQuery:'day in the life of a medical doctor South Africa' },

{ id:'pharmacist', name:'Pharmacist', faculty:'health',
  blurb:'Dispenses medication, advises patients, and ensures the safe and effective use of medicines.',
  dayInLife:'Dispensing prescriptions, patient counselling, stock and compliance management.',
  riasec:['I','C'], strengths:['sciences','maths','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'},{subject:'Life Sciences',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:65},{subject:'Physical Sciences',pct:65}],
  apsGuidance:{typical:'32–38', note:'Competitive but generally more accessible than Medicine.'},
  pathways:[{type:'University', qualification:'Bachelor of Pharmacy (BPharm)', duration:'4 years + 1 year internship + board exam'}],
  institutions:{universities:['University of the Witwatersrand (Wits)','Rhodes University (RU)','University of the Western Cape (UWC)','North-West University (NWU)'], utech:['Tshwane University of Technology (TUT)'], tvet:false},
  applicationNotes:'Register with the South African Pharmacy Council (SAPC) after qualifying.',
  videoQuery:'day in the life of a pharmacist South Africa' },

{ id:'physiotherapist', name:'Physiotherapist', faculty:'health',
  blurb:'Helps patients recover movement and manage pain after injury, illness or surgery.',
  dayInLife:'Hands-on treatment sessions, assessing patients, and designing rehabilitation programmes.',
  riasec:['S','R'], strengths:['sciences','practical','language'],
  requiredSubjects:[{subject:'Physical Sciences',necessity:'required'},{subject:'Life Sciences',necessity:'required'},{subject:'Mathematics',necessity:'recommended'}],
  recommendedMarks:[{subject:'Life Sciences',pct:65},{subject:'Physical Sciences',pct:60}],
  apsGuidance:{typical:'32–38', note:'Selection is very competitive due to limited places.'},
  pathways:[{type:'University', qualification:'Bachelor of Physiotherapy', duration:'4 years'}],
  institutions:{universities:['University of the Witwatersrand (Wits)','University of Cape Town (UCT)','Stellenbosch University (SU)','University of the Free State (UFS)'], utech:[], tvet:false},
  applicationNotes:'Register with the HPCSA after qualifying. A great fit for learners who like both science and working closely with people.',
  videoQuery:'day in the life of a physiotherapist' },

{ id:'dentist', name:'Dentist', faculty:'health',
  blurb:'Diagnoses and treats problems with teeth, gums and the mouth.',
  dayInLife:'Patient consultations, procedures, and practice management.',
  riasec:['I','S'], strengths:['sciences','practical','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'},{subject:'Life Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Physical Sciences',pct:65},{subject:'Life Sciences',pct:65}],
  apsGuidance:{typical:'34–40', note:'Very competitive; limited places nationally.'},
  pathways:[{type:'University', qualification:'Bachelor of Dental Surgery (BDS/BChD)', duration:'5 years'}],
  institutions:{universities:['University of the Witwatersrand (Wits)','University of Pretoria (UP)','University of the Western Cape (UWC)','Sefako Makgatho Health Sciences University (SMU)'], utech:[], tvet:false},
  applicationNotes:'Register with the HPCSA after qualifying.',
  videoQuery:'day in the life of a dentist' },

{ id:'biomedical-scientist', name:'Biomedical Scientist / Medical Technologist', faculty:'health',
  blurb:'Runs laboratory tests that help doctors diagnose and monitor disease.',
  dayInLife:'Analysing blood, tissue and other samples using laboratory equipment and quality-control processes.',
  riasec:['I','C'], strengths:['sciences','problem'],
  requiredSubjects:[{subject:'Physical Sciences',necessity:'required'},{subject:'Life Sciences',necessity:'required'},{subject:'Mathematics',necessity:'recommended'}],
  recommendedMarks:[{subject:'Life Sciences',pct:60},{subject:'Physical Sciences',pct:60}],
  apsGuidance:{typical:'28–34', note:'A strong, less crowded entry point into the health sciences field.'},
  pathways:[
    {type:'University', qualification:'BSc Medical Science / Biomedical Sciences', duration:'3–4 years'},
    {type:'TVET', qualification:'National Diploma: Biomedical Technology', duration:'3 years + internship'},
  ],
  institutions:{universities:['University of Pretoria (UP)','University of the Free State (UFS)','University of the Witwatersrand (Wits)'], utech:['Central University of Technology (CUT)'], tvet:true},
  applicationNotes:'Register with the HPCSA. A good STEM-aligned route into healthcare without the extreme competitiveness of Medicine.',
  videoQuery:'what does a medical laboratory scientist do' },

// ---------------- NATURAL SCIENCES ----------------
{ id:'environmental-scientist', name:'Environmental Scientist', faculty:'natsci',
  blurb:'Studies ecosystems and human impact on the environment, and advises on sustainability and conservation.',
  dayInLife:'Fieldwork, sample analysis, writing environmental impact reports, and policy research.',
  riasec:['I','R'], strengths:['sciences','problem','practical'],
  requiredSubjects:[{subject:'Life Sciences',necessity:'required'},{subject:'Physical Sciences',necessity:'recommended'},{subject:'Geography',necessity:'recommended'}],
  recommendedMarks:[{subject:'Life Sciences',pct:60}],
  apsGuidance:{typical:'26–34', note:'Wide range of programmes with varying entry requirements.'},
  pathways:[{type:'University', qualification:'BSc Environmental Science', duration:'3 years, often + Honours'}],
  institutions:{universities:['University of Cape Town (UCT)','Stellenbosch University (SU)','North-West University (NWU)','Rhodes University (RU)'], utech:[], tvet:false},
  applicationNotes:'Field-based degree — outdoor fieldwork is often a core part of study.',
  videoQuery:'what does an environmental scientist do' },

{ id:'geologist', name:'Geologist', faculty:'natsci',
  blurb:'Studies the Earth\'s structure and materials — vital for mining, water, energy and construction industries.',
  dayInLife:'Fieldwork and sample collection, lab analysis, and mapping geological formations.',
  riasec:['I','R'], strengths:['sciences','maths','practical'],
  requiredSubjects:[{subject:'Physical Sciences',necessity:'required'},{subject:'Mathematics',necessity:'required'}],
  recommendedMarks:[{subject:'Physical Sciences',pct:60},{subject:'Mathematics',pct:60}],
  apsGuidance:{typical:'28–34', note:'South Africa\'s mining industry offers strong local demand for geoscience graduates.'},
  pathways:[{type:'University', qualification:'BSc Geology / Geological Sciences', duration:'3 years, often + Honours'}],
  institutions:{universities:['University of the Witwatersrand (Wits)','University of Pretoria (UP)','Stellenbosch University (SU)'], utech:[], tvet:false},
  applicationNotes:'Register with the South African Council for Natural Scientific Professions (SACNASP) once qualified.',
  videoQuery:'what does a geologist do South Africa mining' },

{ id:'biotechnologist', name:'Biotechnologist', faculty:'natsci',
  blurb:'Uses living organisms and biological processes to develop products in medicine, agriculture and industry.',
  dayInLife:'Laboratory research, experiments, data analysis and product development.',
  riasec:['I','C'], strengths:['sciences','problem','maths'],
  requiredSubjects:[{subject:'Life Sciences',necessity:'required'},{subject:'Physical Sciences',necessity:'required'},{subject:'Mathematics',necessity:'recommended'}],
  recommendedMarks:[{subject:'Life Sciences',pct:65},{subject:'Physical Sciences',pct:60}],
  apsGuidance:{typical:'28–36', note:'A growing field linked to medicine, agriculture and industrial science.'},
  pathways:[{type:'University', qualification:'BSc Biotechnology / Microbiology', duration:'3 years, often + Honours'}],
  institutions:{universities:['University of the Free State (UFS)','University of Pretoria (UP)','University of the Western Cape (UWC)'], utech:['Cape Peninsula University of Technology (CPUT)'], tvet:false},
  applicationNotes:'Postgraduate study (Honours/Masters) is common for research-focused biotechnology careers.',
  videoQuery:'what does a biotechnologist do' },

// ---------------- BUILT ENVIRONMENT ----------------
{ id:'architect', name:'Architect', faculty:'built',
  blurb:'Designs buildings and spaces, balancing function, safety, beauty and sustainability.',
  dayInLife:'Sketching and drafting designs, client meetings, site visits, and coordinating with engineers.',
  riasec:['A','R'], strengths:['creative','maths','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Engineering Graphics and Design',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:60}],
  apsGuidance:{typical:'30–38', note:'A portfolio or drawing test is often required in addition to NSC marks.'},
  pathways:[{type:'University', qualification:'Bachelor of Architecture / BAS', duration:'3 years + 2 years professional (M Arch)'}],
  institutions:{universities:['University of Cape Town (UCT)','University of Pretoria (UP)','University of the Witwatersrand (Wits)','University of Johannesburg (UJ)'], utech:['Cape Peninsula University of Technology (CPUT)'], tvet:false},
  applicationNotes:'Register with the South African Council for the Architectural Profession (SACAP). A strong choice for learners who enjoy both maths and creative design.',
  videoQuery:'day in the life of an architect South Africa' },

{ id:'quantity-surveyor', name:'Quantity Surveyor', faculty:'built',
  blurb:'Manages the costs and contracts of construction projects from planning through to completion.',
  dayInLife:'Estimating costs, preparing tender documents, and managing budgets on construction sites.',
  riasec:['C','E'], strengths:['maths','problem','leadership'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:60}],
  apsGuidance:{typical:'28–34', note:'Strong graduate employment rate in South Africa\'s construction sector.'},
  pathways:[{type:'University', qualification:'BSc Quantity Surveying / Construction Studies', duration:'3–4 years'}],
  institutions:{universities:['University of Cape Town (UCT)','University of Pretoria (UP)','University of the Witwatersrand (Wits)','Nelson Mandela University (NMU)'], utech:['Durban University of Technology (DUT)'], tvet:true},
  applicationNotes:'Register with the South African Council for the Quantity Surveying Profession (SACQSP).',
  videoQuery:'what does a quantity surveyor do' },

{ id:'urban-planner', name:'Urban & Regional Planner', faculty:'built',
  blurb:'Plans how towns and cities grow — land use, transport, housing and public spaces.',
  dayInLife:'Analysing data and maps, community consultations, and drafting development plans.',
  riasec:['I','S'], strengths:['problem','language','leadership'],
  requiredSubjects:[{subject:'Geography',necessity:'recommended'},{subject:'Mathematics',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:55}],
  apsGuidance:{typical:'26–32', note:'A good fit for learners interested in both people and systems-level problem solving.'},
  pathways:[{type:'University', qualification:'BSc/BA Urban and Regional Planning', duration:'3–4 years'}],
  institutions:{universities:['University of the Witwatersrand (Wits)','University of Cape Town (UCT)','University of Pretoria (UP)'], utech:[], tvet:false},
  applicationNotes:'Register with the South African Council for Planners (SACPLAN) once qualified.',
  videoQuery:'what does an urban planner do' },

// ---------------- AGRICULTURE ----------------
{ id:'agricultural-scientist', name:'Agricultural Scientist (Agronomist)', faculty:'agri',
  blurb:'Researches and improves crop production, soil health and farming methods.',
  dayInLife:'Field trials, soil and plant sampling, lab analysis, and advising farmers on best practice.',
  riasec:['I','R'], strengths:['sciences','problem','practical'],
  requiredSubjects:[{subject:'Life Sciences',necessity:'required'},{subject:'Physical Sciences',necessity:'recommended'},{subject:'Agricultural Sciences',necessity:'recommended'}],
  recommendedMarks:[{subject:'Life Sciences',pct:60}],
  apsGuidance:{typical:'26–32', note:'South Africa has strong agricultural science faculties supporting the farming sector.'},
  pathways:[{type:'University', qualification:'BSc Agriculture (Agronomy)', duration:'3–4 years, often + Honours'}],
  institutions:{universities:['University of Pretoria (UP)','Stellenbosch University (SU)','University of the Free State (UFS)','North-West University (NWU)'], utech:[], tvet:true},
  applicationNotes:'Register with SACNASP. Bursaries from agricultural companies and government are common for this field.',
  videoQuery:'what does an agricultural scientist do' },

{ id:'agricultural-engineer', name:'Agricultural Engineer', faculty:'agri',
  blurb:'Designs machinery, irrigation and systems that make farming more efficient and sustainable.',
  dayInLife:'Designing equipment or irrigation systems, testing machinery, and on-farm problem solving.',
  riasec:['R','I'], strengths:['maths','sciences','practical'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Physical Sciences',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:65},{subject:'Physical Sciences',pct:60}],
  apsGuidance:{typical:'28–36', note:'A niche but valuable engineering specialisation for South Africa\'s agricultural economy.'},
  pathways:[{type:'University', qualification:'BEng / BSc (Agric) Agricultural Engineering', duration:'4 years'}],
  institutions:{universities:['University of Pretoria (UP)','University of KwaZulu-Natal (UKZN)'], utech:[], tvet:false},
  applicationNotes:'ECSA registration after graduating, similar to other engineering disciplines.',
  videoQuery:'what does an agricultural engineer do' },

// ---------------- FINANCE / ACTUARIAL / QUANT ----------------
{ id:'actuary', name:'Actuary', faculty:'finance',
  blurb:'Uses maths, statistics and financial theory to assess and manage risk — for insurers, pensions and investments.',
  dayInLife:'Building statistical models, pricing risk, and presenting findings to business leaders.',
  riasec:['I','C'], strengths:['maths','problem','tech'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:85}],
  apsGuidance:{typical:'38–42', note:'Requires one of the highest Mathematics marks of any career path — most programmes look closely at your Maths % directly, not just APS.'},
  pathways:[{type:'University', qualification:'BSc/BCom Actuarial Science', duration:'3–4 years + professional actuarial exams'}],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)','University of Pretoria (UP)'], utech:[], tvet:false},
  applicationNotes:'Professional qualification through the Actuarial Society of South Africa (ASSA) continues after your degree. Mathematical Literacy is not accepted for this pathway.',
  videoQuery:'what does an actuary do South Africa' },

{ id:'chartered-accountant', name:'Chartered Accountant CA(SA)', faculty:'finance',
  blurb:'Provides financial reporting, auditing, tax and strategic advice to businesses and organisations.',
  dayInLife:'Reviewing financial statements, advising clients, and ensuring compliance with financial regulations.',
  riasec:['C','E'], strengths:['maths','problem','leadership'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Accounting',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:70}],
  apsGuidance:{typical:'32–38', note:'Programme must be SAICA-accredited to lead to the CA(SA) qualification.'},
  pathways:[{type:'University', qualification:'BCom Accounting (CA stream) + CTA + articles', duration:'3 years degree + 1 year CTA + 3 years articles + board exams'}],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)','University of Pretoria (UP)','University of Johannesburg (UJ)'], utech:[], tvet:false},
  applicationNotes:'Registered with SAICA (South African Institute of Chartered Accountants). Accounting as an NSC subject is helpful but not always compulsory — check each university\'s specific rule.',
  videoQuery:'what does a chartered accountant do South Africa' },

{ id:'financial-analyst', name:'Financial / Investment Analyst', faculty:'finance',
  blurb:'Researches companies, markets and investments to guide financial decision-making.',
  dayInLife:'Building financial models, researching companies and markets, and writing investment reports.',
  riasec:['E','C'], strengths:['maths','problem','leadership'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:70}],
  apsGuidance:{typical:'30–36', note:'Often entered via BCom Finance, Economics or Investment Management degrees.'},
  pathways:[{type:'University', qualification:'BCom Finance / Investment Management', duration:'3 years, often + CFA designation'}],
  institutions:{universities:['University of Cape Town (UCT)','University of Pretoria (UP)','University of Stellenbosch (SU)','University of the Witwatersrand (Wits)'], utech:[], tvet:false},
  applicationNotes:'The CFA (Chartered Financial Analyst) designation is a valuable add-on after your degree for global finance careers.',
  videoQuery:'what does a financial analyst do' },

{ id:'quantitative-analyst', name:'Quantitative Analyst ("Quant")', faculty:'finance',
  blurb:'Builds mathematical models to price financial instruments and manage investment risk.',
  dayInLife:'Coding trading and risk models, analysing market data, and testing mathematical strategies.',
  riasec:['I','C'], strengths:['maths','tech','problem'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'}],
  recommendedMarks:[{subject:'Mathematics',pct:80}],
  apsGuidance:{typical:'36–42', note:'Extremely maths-intensive — usually requires postgraduate study (Honours/Masters in Maths, Stats, Actuarial Science or Financial Engineering).'},
  pathways:[{type:'University', qualification:'BSc Mathematics/Statistics/Actuarial Science + postgraduate specialisation', duration:'3 years + Honours/Masters'}],
  institutions:{universities:['University of Cape Town (UCT)','University of the Witwatersrand (Wits)','Stellenbosch University (SU)'], utech:[], tvet:false},
  applicationNotes:'A rare, highly specialised career combining advanced mathematics with coding and finance.',
  videoQuery:'what does a quantitative analyst do' },

{ id:'economist', name:'Economist', faculty:'finance',
  blurb:'Studies how economies work — analysing trends in trade, employment, prices and policy.',
  dayInLife:'Analysing economic data, building forecasts, and writing policy or research reports.',
  riasec:['I','C'], strengths:['maths','problem','language'],
  requiredSubjects:[{subject:'Mathematics',necessity:'required'},{subject:'Economics',necessity:'recommended'}],
  recommendedMarks:[{subject:'Mathematics',pct:65}],
  apsGuidance:{typical:'28–34', note:'Entry requirements vary depending on whether the degree is BCom or BA-based.'},
  pathways:[{type:'University', qualification:'BCom/BA Economics', duration:'3 years, often + Honours for research/policy roles'}],
  institutions:{universities:['University of Cape Town (UCT)','University of Pretoria (UP)','University of Stellenbosch (SU)','University of the Witwatersrand (Wits)'], utech:[], tvet:false},
  applicationNotes:'Roles exist in government (e.g. National Treasury, SARB), banks, and research institutions.',
  videoQuery:'what does an economist do' },
];

// NSC 7-point achievement scale used for APS calculations (general guidance — verify per institution)
const NSC_LEVELS = [
  { level:7, min:80, max:100, desc:'Outstanding' },
  { level:6, min:70, max:79,  desc:'Meritorious' },
  { level:5, min:60, max:69,  desc:'Substantial' },
  { level:4, min:50, max:59,  desc:'Adequate' },
  { level:3, min:40, max:49,  desc:'Moderate' },
  { level:2, min:30, max:39,  desc:'Elementary' },
  { level:1, min:0,  max:29,  desc:'Not achieved' },
];
function nscLevel(pct){
  pct = Math.max(0, Math.min(100, Number(pct)||0));
  const row = NSC_LEVELS.find(r => pct >= r.min && pct <= r.max) || NSC_LEVELS[NSC_LEVELS.length-1];
  return row.level;
}
